[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  
[build.processing]
  skip_processing = true  
  
[[plugins]]
  package = "@netlify/plugin-nextjs"
